name: Publish Prod
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+\+upstream*'
      - '[0-9]+.[0-9]+.[0-9]+-rc*\+upstream*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check release type
        id: check_release
        run: |
          TYPE="release-candidate"
          echo "type: ${TYPE}"
          echo "RELEASE_SUFFIX=-rc" >> $GITHUB_ENV
          echo "type=${TYPE}" >> $GITHUB_OUTPUT
      - name: Update chart name for RC versions
        if: needs.build.outputs.release_type == 'release-candidate'
        run: echo "suffix is ${{ env.RELEASE_SUFFIX }}"
