name: Publish Prod
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+\+upstream*'
      - '[0-9]+.[0-9]+.[0-9]+-rc*\+upstream*'

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      release_type: ${{ steps.check_release.outputs.type }}
    steps:
      - name: set env var for test
        run: echo "TAG_TEST=123" >> $GITHUB_ENV
      - name: check ref
        run: |
          if [[ ${GITHUB_REF} =~ "rc" ]]; then
            TYPE="release-candidate"
          fi
          echo "echo ref is $GITHUB_REF, type is $TYPE"
      - name: Check release type
        id: check_release
        run: |
          TYPE="release-candidate"
          echo "tag test is $TAG_TEST"
          echo "type: ${TYPE}"
          echo "RELEASE_SUFFIX=-rc" >> $GITHUB_ENV
          echo "type=${TYPE}" >> $GITHUB_OUTPUT
      - name: Update chart name for RC versions
        if: steps.check_release.outputs.type == 'release-candidate'
        run: echo "suffix is ${{ env.RELEASE_SUFFIX }}"
  second_job:
    runs-on: ubuntu-latest
    needs: [release]
    if: needs.release.outputs.release_type == 'release-candidate'
    steps:
      - name: print
        run: echo 'well done'
