name: Publish RC
on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      - name: tets yq
        run: yq e -i '.name = "chart-name-rc"' Chart.yaml
      - name: print
        run: cat Chart.yaml
