name: Publish RC
on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: tets yq
        run: yq e -i '.name = "chart-name-rc"' Chart.yaml
      - name: print
        run: cat Chart.yaml
